name: Simple iOS Build

on:
  workflow_dispatch:  # Manual trigger only

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.0'
    
    - run: flutter pub get
    
    - run: flutter build ios --release --no-codesign
    
    - run: |
        mkdir Payload
        cp -r build/ios/iphoneos/Runner.app Payload/
        zip -r app.ipa Payload/
        
    - uses: actions/upload-artifact@v4
      with:
        name: ios-app
        path: app.ipa